In [2]:
data = 123
data

123

In [3]:
my_list = [1,2,3]
len(my_list)

3

In [4]:
import numpy as np

In [5]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [6]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [7]:
# numpy를 이용하여 array 정의하기
# 1. 위에서 만든 python list를 이용
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [8]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [9]:
# 2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [10]:
arr2.shape

(5,)

In [11]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int32')

In [12]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [13]:
arr3.shape

(5,)

In [14]:
arr3.dtype

dtype('float64')

In [15]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
arr4.shape

(4, 3)

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.

In [20]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

In [26]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr1.shape

(2, 3)

In [28]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [29]:
arr2.shape

(2, 3)

In [30]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [31]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [32]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [33]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [34]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr1.shape

(2, 3)

In [36]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [37]:
arr3.shape

(3,)

In [38]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [39]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [40]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [42]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# 0번째 요소
arr1[0]

0

In [44]:
# 3번째 요소
arr1[3]

3

In [45]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [46]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [49]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [50]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

In [51]:
# 모든 행의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])